# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-07-23 16:54
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_time', models.DateTimeField(default=datetime.datetime(2019, 7, 23, 16, 54, 44, 247703, tzinfo=utc))),
                ('approved_time', models.DateTimeField(blank=True)),
                ('approved_comment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('description', models.TextField()),
                ('created_time', models.DateTimeField(default=datetime.datetime(2019, 7, 23, 16, 54, 44, 246704, tzinfo=utc))),
                ('approved_time', models.DateTimeField(blank=True)),
                ('approved_thread', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='discussion_forum.Thread'),
        ),
    ]
