# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-07-23 16:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_forum', '0002_auto_20190723_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 23, 16, 55, 9, 9204, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='thread',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 23, 16, 55, 9, 9204, tzinfo=utc)),
        ),
    ]
