# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-07-30 22:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_forum', '0005_auto_20190723_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 30, 22, 7, 36, 429135, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='thread',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 30, 22, 7, 36, 428104, tzinfo=utc)),
        ),
    ]
